apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-project
spec:
  replicas: 2
  strategy:
    type: Rolling
  selector:
    matchLabels:
      app: maven-project
  template:
    metadata:
      name: maven-project
      labels:
        app: maven-project
    spec:
      containers:
        - name: maven-project
          image: mdabrar4devops/maven-project
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: maven-project-service
spec:
  selector:
    app: maven-project
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
